---
-
  hosts: client
  vars:
    container_count: 4
    container_name: redhatdocker
    container_image: prashantojha01/customer:v1
    customer_command: sleep 1
  tasks:
    - name: Import a key from a url
      rpm_key:
        state: present
        key: "https://download.docker.com/linux/rhel/gpg"
    - name: install yum-util
      yum:
        name: yum-utils
        state: latest
    - name: set up repo
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/rhel/docker-ce.repo
    